apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fio-prom-exporter
  name: fio-prom-exporter
  namespace: my-ripsaw 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fio-prom-exporter
  template:
    metadata:
      labels:
        app: fio-prom-exporter
    spec:
      containers:
      - name: fio-prom-exporter
        image: pool6-infra1.practice.redhat.com:9446/canary/fio-prom-exporter:v0.1.2 
        imagePullPolicy: IfNotPresent
        env:
        - name: PYTHONUNBUFFERED
          value: "0"
        command:
        - /bin/sh
        args:
        - '-c'
        - 'python3 /exporter/bin/prometheusclient.py'
        #- 'tail -f /dev/null'
        volumeMounts:
        - mountPath: /mnt/fio
          name: data-volume
        - mountPath: /exporter/config
          name: metrics-conf-volume 
        - mountPath: /exporter/bin
          name: prom-client-volume 
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: fio-data-pvc
          readOnly: false 
      - name: prom-client-volume
        configMap:
          name: fio-prom-client
      - name: metrics-conf-volume
        configMap:
          name: fio-metrics-conf
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: fio-prom-exporter
  name: fio-prom-exporter
  namespace: my-ripsaw 
spec:
  ports:
  - port: 8585 
    protocol: TCP
    targetPort: 8000 
    name: web 
  selector:
    app: fio-prom-exporter
  type: ClusterIP
