apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: fio-monitor
  name: fio-monitor
  namespace: my-ripsaw 
spec:
  endpoints:
  - interval: 600s
    port: web 
    scheme: http
  selector:
    matchLabels:
      app: fio-prom-exporter
