apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ceph-canary 
  namespace: ceph-canary
rules:
- apiGroups:
  - ""
  resources:
  - daemonsets
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - pods
  - pods/log
  - pods/exec
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get

