apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ceph-canary 
  namespace: ceph-canary
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ceph-canary 
subjects:
- kind: ServiceAccount
  name: ceph-canary 
  namespace: ceph-canary
