apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: fio-cronjob 
spec:
  schedule: "*/10 * * * *"
  successfulJobsHistoryLimit: 0 
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ose-cli
            image: pool6-infra1.practice.redhat.com:9446/openshift4/ose-cli:v4.7
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            args:
            - '-c'
            - 'mnt/bin/fio_canary.sh'
            volumeMounts: 
            - name: fio-canary-volume 
              mountPath: /mnt/bin 
            - name: config-fioloadpvc-volume 
              mountPath: /mnt/config-fioloadpvc
            - name: config-fiopod-volume 
              mountPath: /mnt/config-fiopod
            - name: data-volume
              mountPath: /mnt/fio
          volumes:
          - name: data-volume
            persistentVolumeClaim:
              claimName: fio-data-pvc
              readOnly: false
          - name: fio-canary-volume
            configMap:
              name: fio-canary
              defaultMode: 0755
          - name: config-fioloadpvc-volume
            configMap:
              name: fio-load-pvc
          - name: config-fiopod-volume
            configMap:
              name: fio-pod
          restartPolicy: OnFailure
