apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fio-load-pvc 
  namespace: ceph-canary 
spec:
  storageClassName: ocs-storagecluster-ceph-rbd 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G 
