apiVersion: v1
kind: Pod 
metadata:
  name: osecli-pod
  namespace: ceph-canary 
spec:
  serviceAccountName: ceph-canary
  containers:
  - name: ose-cli
    image: OSECLI_IMAGE_REPO 
    imagePullPolicy: IfNotPresent
    command:
    - /bin/sh
    args:
    - '-c'
    #- '/fio/bin/fio_canary.sh'
    - 'tail -f /dev/null'
    volumeMounts: 
    - name: fio-canary-volume 
      mountPath: /fio/bin 
    - name: config-fioloadpvc-volume 
      mountPath: /fio/config-fioloadpvc
    - name: config-fiopod-volume 
      mountPath: /fio/config-fiopod
  volumes:
  - name: fio-canary-volume
    configMap:
      name: fio-canary
      defaultMode: 0755
  - name: config-fioloadpvc-volume
    configMap:
      name: fio-load-pvc
  - name: config-fiopod-volume
    configMap:
      name: fio-pod
  restartPolicy: OnFailure
